server {
    server_name brindoujunior.com www.brindoujunior.com;

    root /var/www/brindoujunior;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/brindoujunior;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/brindoujunior.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/brindoujunior.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}

server {
    if ($host = www.brindoujunior.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    if ($host = brindoujunior.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name brindoujunior.com www.brindoujunior.com;
    return 404; # managed by Certbot
}
